[package]
name = "mendels_First_Law"
version = "0.1.0"
authors = ["Paul Grant <paul_grant@med.unc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.5 "
rsgenetic = "^1.8.0"